AllCops:
  DisplayCopNames: true
  NewCops: enable
  SuggestExtensions: false

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec_rails
  - rubocop-factory_bot

### Lint ###
Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

### Style ###
Style/AccessorGrouping:
  Enabled: true
  EnforcedStyle: separated

Style/BlockDelimiters:
  Enabled: true
  EnforcedStyle: semantic
  AllowBracesOnProceduralOneLiners: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/GlobalVars:
  AllowedVariables: [$current_dataset]

Style/GuardClause:
  Enabled: false

Style/IfInsideElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 9

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/OptionalBooleanParameter:
  Enabled: false

Style/SignalException:
  EnforcedStyle: semantic

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '()'
    '%i': '()'
    '%q': '()'
    '%Q': '()'
    '%r': '{}'
    '%s': '()'
    '%w': '()'
    '%W': '()'
    '%x': '()'

Style/RescueStandardError:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/SymbolArray:
  Enabled: false

### Layout ###
Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

### Naming ###
Naming/PredicatePrefix:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Naming/PredicateMethod:
  Enabled: false

### Metrics ###
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

### Rails ###
Rails:
  Enabled: true

Rails/Blank:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/SquishedSQLHeredocs:
  Enabled: false

Rails/RedundantActiveRecordAllMethod:
  Enabled: false

Rails/DynamicFindBy:
  AllowedMethods:
    - find_by_id
    - find_by_id!
    - find_by_ids
    - find_by_ids!

Rails/InverseOf:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/FindEach:
  Enabled: false

### Performance ###
Performance/CollectionLiteralInLoop:
  Enabled: false

### RSpec ###
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false
